// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxqmhvdbamkbnutrqdja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4cW1odmRiYW1rYm51dHJxZGphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODE5NjMsImV4cCI6MjA2MDA1Nzk2M30.cjPlEfsvDL4bAaVjHFx1NxscXrFH9cgOPwawMrBnqjo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);